name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability.
version: 6.5.1
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface:
    git:
      url: git@github.com:stequar/speech_to_text.git
      path: speech_to_text_platform_interface
      ref: feature/flutter-3.7
  json_annotation: ^4.0.0
  clock: ^1.0.1
  pedantic: ^1.9.2
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  fake_async: ^1.3.1
  mockito: ^5.4.1
  plugin_platform_interface: ^2.1.4
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
      web:
        pluginClass: SpeechToTextPlugin
        fileName: speech_to_text_web.dart
      macos:
        default_package: speech_to_text_macos
